### ISSUE TITLE
white screen flashing triggering from api 1.10.2

### ISSUE THREAD

**Issue by SDUBZ** [AtomicBlom/ShearMadness#30]
Notifying sheep chiseled - entity EntitySheep['Sheep'/9028083, l='New World', x=387.24, y=4.00, z=-520.38]
[15:31:16] [Client thread/ERROR]: Couldn't render entity
java.lang.NullPointerException
    at com.github.atomicblom.shearmadness.api.rendering.VertexConsumer.put(VertexConsumer.java:115) ~[VertexConsumer.class:?]
    at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:85) ~[UnpackedBakedQuad.class:?]
    at com.github.atomicblom.shearmadness.api.rendering.EntityMesh.func_178780_a(EntityMesh.java:57) ~[EntityMesh.class:?]
    at net.minecraft.client.model.ModelRenderer.func_78788_d(ModelRenderer.java:279) ~[blf.class:?]
    at net.minecraft.client.model.ModelRenderer.func_78785_a(ModelRenderer.java:119) ~[blf.class:?]
    at net.minecraft.client.model.ModelQuadruped.func_78088_a(SourceFile:59) ~[bka.class:?]
    at com.github.atomicblom.shearmadness.rendering.LayerSheepChiselWool.doRenderLayer(LayerSheepChiselWool.java:86) ~[LayerSheepChiselWool.class:?]
    at com.github.atomicblom.shearmadness.rendering.LayerSheepChiselWool.func_177141_a(LayerSheepChiselWool.java:24) ~[LayerSheepChiselWool.class:?]
    at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:436) ~[bsy.class:?]
    at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:188) [bsy.class:?]
    at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41) [btb.class:?]
    at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16) [btb.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366) [bsh.class:?]
    at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350) [bsh.class:?]
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:623) [boh.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315) [bnz.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229) [bnz.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038) [bnz.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

forge:1.10.2-2088
latestlog: 
[latest.txt](https://github.com/AtomicBlom/ShearMadness/files/476129/latest.txt)

**Comment by AtomicBlom** [comment]
Heya sdubz,

Version 1.2.1 was just approved on CurseForge which should prevent any flashing white screens, but you may find that the sheep doesn't render correctly when it would have happened.

I'd be mighty interested in a log if you notice a sheep that should have worked, but is naked or missing polygons.

--Steve

**Comment by AtomicBlom** [comment]
Turns out I was using the VertexFormat from the destination, not the source. Fixed in source, will be out with release 1.2.2
