### ISSUE TITLE
EntityItem cannot be cast to EntityLiving

### ISSUE THREAD

**Issue by AtomicBlom** [AtomicBlom/ShearMadness#36]
OpenEye pointed me at this crash:
https://openeye.openmods.info/crashes/0cac793bddd8ce106e5320489337a33e

    java.lang.ClassCastException: net.minecraft.entity.item.EntityItem cannot be cast to net.minecraft.entity.EntityLiving

    at com.github.atomicblom.shearmadness.proxy.CommonForgeEventProxy.onCommonEntityJoinWorldEvent(CommonForgeEventProxy.java:162)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_0_CommonForgeEventProxy_onCommonEntityJoinWorldEvent_EntityJoinWorldEvent.invoke(.dynamic:-1)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraft.world.WorldServer.loadEntities(WorldServer.java:1071)
    at net.minecraft.world.chunk.Chunk.onChunkLoad(Chunk.java:845)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:104)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:86)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:132)
    at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:298)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:174)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:197)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(Thread.java:745)

Related code:
https://github.com/AtomicBlom/ShearMadness/blob/master/src/main/java/com/github/atomicblom/shearmadness/proxy/CommonForgeEventProxy.java#L147-L166

**Comment by AtomicBlom** [comment]
Fixed in recent builds.
