### ISSUE TITLE
Crash while chiseling sheep.

### ISSUE THREAD

**Issue by ryantheleach** [AtomicBlom/ShearMadness#39]
[crash-2017-10-22_05.17.39-client.txt](https://github.com/AtomicBlom/ShearMadness/files/1404375/crash-2017-10-22_05.17.39-client.txt)
```
UCHIJA	chisel{MC1.10.2-0.0.14.33} [Chisel] (Chisel-MC1.10.2-0.0.14.33.jar) 
UCHIJA	shearmadness{1.10.2} [Shear Madness] (shearmadness-1.10.2-1.7.0.4.jar) 
Launched Version: forge-12.18.3.2477
```

```
Description: Rendering entity in world

com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: team/chisel/client/ChiselExtendedState
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at com.github.atomicblom.shearmadness.rendering.LayerSheepChiselWool.doRenderLayer(LayerSheepChiselWool.java:72)
	at com.github.atomicblom.shearmadness.rendering.LayerSheepChiselWool.func_177141_a(LayerSheepChiselWool.java:33)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:436)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:188)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:624)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: team/chisel/client/ChiselExtendedState
	at com.github.atomicblom.shearmadness.variations.chisel.visuals.DefaultChiselModelMaker.getChiselBodyModelRenderer(DefaultChiselModelMaker.java:53)
	at com.github.atomicblom.shearmadness.variations.chisel.visuals.DefaultChiselModelMaker.lambda$createModel$31(DefaultChiselModelMaker.java:40)
	at com.github.atomicblom.shearmadness.variations.chisel.visuals.DefaultChiselModelMaker$$Lambda$1179/1726409658.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.atomicblom.shearmadness.variations.chisel.visuals.DefaultChiselModelMaker.createModel(DefaultChiselModelMaker.java:40)
	at com.github.atomicblom.shearmadness.rendering.LayerSheepChiselWool.lambda$doRenderLayer$64(LayerSheepChiselWool.java:80)
	at com.github.atomicblom.shearmadness.rendering.LayerSheepChiselWool$$Lambda$1178/1238685131.call(Unknown Source)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 23 more
Caused by: java.lang.ClassNotFoundException: team.chisel.client.ChiselExtendedState
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NullPointerException
```

**Comment by AtomicBlom** [comment]
Fixed in 1.7.1
